variables:
  DOCKER_REGISTRY: 574819725898.dkr.ecr.eu-west-3.amazonaws.com
  AWS_DEFAULT_REGION: eu-west-3
  IMAGE_NAME: cantinelanding
  IMAGE_TAG: latest
  DOCKER_HOST: tcp://docker:2375
  APP_VERSION: 2

publish:
  only:
    - develop
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    - aws elasticbeanstalk update-environment --application-name "bartcantinelanding" --environment-name "Bartcantinelanding-env" --version-label=$APP_VERSION